# -*- coding: utf-8 -*-
# Generates API.md - runs in two passes (part A + part B)
import io, os

def make_part_a():
    lines = []
    L = lines.append
    L('# UniToolGUI Plugins - 完整技术文档')
    L('')
    L('> 跨平台 API，支持 Windows / macOS / Linux。推荐入口：NativePlatform 门面类。')
    L('')
    L('---')
    L('')
    L('## 目录')
    L('')
    for s in [
        '0. NativePlatform 统一入口',
        '1. TrayIconService 系统托盘',
        '2. WindowsFileDialog 文件对话框',
        '3. WindowsMessageBox 消息框',
        '4. WindowsClipboard 剪贴板',
        '5. WindowsShell Shell操作',
        '6. WindowsSingleInstance 单实例',
        '7. WindowsHotkey 全局热键',
        '8. WindowsPower 电源控制',
        '9. WindowsRecycleBin 回收站',
        '10. WindowsWindow 窗口控制',
        '11. WindowsStartup 开机自启',
        '12. WindowsSystemInfo 系统信息',
        '13. WindowsToast Toast通知',
        '14. WindowsJumpList',
        '15. WindowsAdmin 管理员检测',
        '16. WindowsTheme 主题DPI',
        '17. ProcessHelper 进程工具',
        '18. 接口层与平台实现',
        '平台支持矩阵',
        '架构说明与优化日志',
    ]:
        L(f'- {s}')
    L('')
    L('---')
    L('')
    L('## 0. NativePlatform 统一入口')
    L('')
    L('平台：Win / Mac / Linux（不支持功能返回空实现，不抛异常）')
    L('')
    L('```csharp')
    L('bool NativePlatform.IsWindows / IsMacOS / IsLinux')
    L('IFileDialog     NativePlatform.FileDialog')
    L('IClipboard      NativePlatform.Clipboard')
    L('IToastService   NativePlatform.Toast')
    L('IMessageBox     NativePlatform.MessageBox')
    L('IShellService   NativePlatform.Shell')
    L('ISingleInstance NativePlatform.SingleInstance')
    L('ITrayService    NativePlatform.Tray')
    L('bool   NativePlatform.ShowToast(title, message, imagePath=null)')
    L('string NativePlatform.OpenFile(title, filter, ext=null, dir=null)')
    L('string NativePlatform.OpenFolder(title, dir=null)')
    L('bool   NativePlatform.OpenUrl(url)')
    L('string NativePlatform.GetClipboard()')
    L('bool   NativePlatform.SetClipboard(text)')
    L('```')
    L('')
    L('```csharp')
    L('if (!NativePlatform.SingleInstance.TryAcquire("MyApp")) { Application.Quit(); return; }')
    L('NativePlatform.Tray.Initialize();')
    L('NativePlatform.Tray.SetTooltip("我的应用");')
    L('NativePlatform.ShowToast("启动", "就绪");')
    L('void OnApplicationQuit() { NativePlatform.SingleInstance.Release(); NativePlatform.Tray.Shutdown(); }')
    L('```')
    L('')
    L('---')
    L('')
    L('## 1. TrayIconService 系统托盘')
    L('')
    L('平台：Win / Mac | 接口：ITrayService | 入口：NativePlatform.Tray')
    L('v2：重构为单文件 #if 多平台，消除三份重复代码。')
    L('')
    L('```csharp')
    L('void Initialize(); void Shutdown();')
    L('void SetTooltip(string tooltip);')
    L('void RegisterMenuItems(IEnumerable<TrayMenuItem> items);')
    L('void UnregisterMenuItems(...); void ClearMenuItems(); void RefreshMenu();')
    L('void ShowMainWindow();')
    L('void ShowBalloonTip(string title, string message, uint iconType=1, uint timeoutMs=5000);')
    L('event Action OnTrayIconCreated / OnTrayIconDestroyed;')
    L('event Action<int> OnHotkeyPressed;  // Win only')
    L('```')
    L('TrayMenuItem: Text, Callback, IsSeparator, IsToggle, Checked')
    L('')
    L('---')
    L('')
    L('## 2. WindowsFileDialog 文件对话框')
    L('')
    L('平台：Win / Mac / Linux | 接口：IFileDialog | 入口：NativePlatform.FileDialog')
    L('v2：macOS 改为 osascript stdin 内联执行，无临时文件；Linux 补全 SaveFilePanel/OpenFolderPanel。')
    L('')
    L('```csharp')
    L('string   CreateFilter(params string[] filterPairs);')
    L('string   OpenFilePanel(string title, string filter, string ext=null, string dir=null);')
    L('string[] OpenFilePanelMulti(string title, string filter, string ext=null, string dir=null);')
    L('string   SaveFilePanel(string title, string filter, string ext=null, string dir=null, string name=null);')
    L('string   OpenFolderPanel(string title, string dir=null);')
    L('```')
    L('')
    L('---')
    L('')
    L('## 3. WindowsMessageBox 消息框')
    L('')
    L('平台：Win / Mac / Linux | 接口：IMessageBox | 入口：NativePlatform.MessageBox')
    L('')
    L('```csharp')
    L('void Info(string text, string caption="信息");')
    L('void Warning(string text, string caption="警告");')
    L('void Error(string text, string caption="错误");')
    L('bool Confirm(string text, string caption="确认");  // true=OK')
    L('bool YesNo(string text, string caption="请选择");  // true=Yes')
    L('int  Show(IntPtr hWnd, string text, string caption, int buttons=0, int icon=0);')
    L('```')
    L('')
    L('---')
    L('')
    L('## 4. WindowsClipboard 剪贴板')
    L('')
    L('平台：Win / Mac / Linux | 接口：IClipboard | 入口：NativePlatform.Clipboard')
    L('')
    L('```csharp')
    L('string GetText(); bool SetText(string text); bool HasText();')
    L('```')
    L('')
    L('---')
    L('')
    L('## 5. WindowsShell Shell操作')
    L('')
    L('平台：Win / Mac / Linux | 接口：IShellService | 入口：NativePlatform.Shell')
    L('')
    L('```csharp')
    L('bool OpenUrl(string url);')
    L('bool OpenFile(string filePath);')
    L('bool OpenFolder(string folderPath, string filePath=null);')
    L('bool Execute(string operation, string filePath, string parameters=null, string workingDir=null);')
    L('```')
    L('')
    L('---')
    L('')
    L('## 6. WindowsSingleInstance 单实例')
    L('')
    L('平台：Win(Global Mutex) / Mac(~/Library/Caches) / Linux(~/.cache)')
    L('接口：ISingleInstance | 入口：NativePlatform.SingleInstance')
    L('v2：Mac/Linux 锁文件从 /tmp 改为用户私有缓存目录，避免系统清理和跨用户污染。')
    L('')
    L('```csharp')
    L('bool TryAcquire(string mutexName=null);  // false=已有实例')
    L('void Release();')
    L('bool IsAnotherInstanceRunning(string mutexName=null);')
    L('```')
    L('')
    L('---')
    L('')
    L('## 7. WindowsHotkey 全局热键')
    L('')
    L('平台：Win only（其他平台同签名空实现，编译不报错）')
    L('v2：补全完整 VK 常量表。')
    L('')
    L('```csharp')
    L('bool   Register(IntPtr hwnd, int id, ModifierKeys modifiers, uint virtualKey);')
    L('bool   Unregister(IntPtr hwnd, int id);')
    L('IntPtr GetUnityWindowHandle();')
    L('// ModifierKeys: None|Alt|Ctrl|Shift|Win|NoRepeat')
    L('// VK.*: F1-F24, A-Z, D0-D9, Numpad0-9, Left/Up/Right/Down,')
    L('//       Home/End/PageUp/PageDown/Insert/Delete, Space/Enter/Escape/Tab/BackSpace,')
    L('//       Media*(NextTrack/PrevTrack/Stop/PlayPause), Volume*(Up/Down/Mute),')
    L('//       Browser*(Back/Forward/Refresh/Stop/Search/Home), Oem*(Semicolon/Plus/Comma/...)')
    L('```')
    L('')
    L('---')
    L('')
    L('## 8. WindowsPower 电源控制')
    L('')
    L('平台：Win / Mac / Linux')
    L('')
    L('```csharp')
    L('void PreventSleep(); void PreventSleepAndDisplay(); void AllowSleep(); void ResetIdleTimer();')
    L('```')
    L('')
    L('---')
    L('')
    L('## 9. WindowsRecycleBin 回收站')
    L('')
    L('平台：Win / Mac / Linux')
    L('')
    L('```csharp')
    L('int MoveToRecycleBin(string path, bool showConfirm=true);   // 0=成功')
    L('int MoveToRecycleBinSilent(string path);  // 多文件：路径以 \\0 分隔')
    L('```')
    return '\n'.join(lines) + '\n'

part_a = make_part_a()
with open(r'd:\UniToolGUI\Assets\Plugins\API.md', 'w', encoding='utf-8') as f:
    f.write(part_a)
print('part_a written, lines:', part_a.count('\n'))
