# -*- coding: utf-8 -*-
import io

def make_part_b():
    lines = []
    L = lines.append
    L('---')
    L('')
    L('## 10. WindowsWindow 窗口控制')
    L('')
    L('平台：Win / Mac(委托 MacWindowPlugin) / Linux X')
    L('v2：Win/Mac 均实现 Minimize/Maximize/Restore/SetOpacity。Mac 通过 NSWindow(dispatch_sync)。')
    L('')
    L('```csharp')
    L('IntPtr GetUnityWindowHandle();')
    L('bool SetTopMost(IntPtr hwnd, bool topMost);')
    L('bool SetPositionAndSize(IntPtr hwnd, int x, int y, int w, int h);')
    L('bool GetPositionAndSize(IntPtr hwnd, out int x, out int y, out int w, out int h);')
    L('bool Minimize(IntPtr hwnd);   // Mac: NSWindow.miniaturize')
    L('bool Maximize(IntPtr hwnd);   // Mac: NSWindow.zoom')
    L('bool Restore(IntPtr hwnd);    // Mac: deminiaturize or zoom toggle')
    L('bool IsMinimized(IntPtr hwnd); bool IsMaximized(IntPtr hwnd);')
    L('bool SetOpacity(IntPtr hwnd, float opacity);  // 0.0~1.0; Mac: alphaValue+setOpaque')
    L('// Unity 便捷方法（无需句柄）：SetUnityWindowTopMost/Rect/Opacity,')
    L('// Minimize/Maximize/Restore/IsMinimized/IsMaximized UnityWindow')
    L('```')
    L('')
    L('```csharp')
    L('WindowsWindow.SetUnityWindowTopMost(true);')
    L('WindowsWindow.SetUnityWindowRect(100, 100, 1280, 720);')
    L('WindowsWindow.SetUnityWindowOpacity(0.9f);')
    L('WindowsWindow.MinimizeUnityWindow();')
    L('```')
    L('')
    L('---')
    L('')
    L('## 11. WindowsStartup 开机自启')
    L('')
    L('平台：Win / Mac / Linux')
    L('')
    L('```csharp')
    L('bool IsStartupEnabled();')
    L('bool EnableStartup(string exePath=null, string keyName=null);')
    L('bool DisableStartup(string keyName=null);')
    L('bool ToggleStartup(string exePath=null);')
    L('```')
    L('')
    L('---')
    L('')
    L('## 12. WindowsSystemInfo 系统信息')
    L('')
    L('平台：Win / Mac / Linux')
    L('')
    L('```csharp')
    L('(int w, int h)                   GetPrimaryScreenSize();')
    L('(int w, int h)                   GetVirtualScreenSize();')
    L('(bool onAC, int pct, int remSec) GetBatteryInfo();')
    L('uint GetIdleTimeSeconds(); string GetComputerName(); string GetUserName();')
    L('```')
    L('')
    L('---')
    L('')
    L('## 13. WindowsToast Toast通知')
    L('')
    L('平台：Win / Mac / Linux | 接口：IToastService | 入口：NativePlatform.Toast')
    L('v2：Windows 改为内联 PowerShell -Command，无临时 .ps1 文件。')
    L('')
    L('```csharp')
    L('bool Show(string title, string message, string imagePath=null);')
    L('// Win: inline PS/WinRT  Mac: osascript  Linux: notify-send')
    L('```')
    L('')
    L('---')
    L('')
    L('## 14. WindowsJumpList')
    L('')
    L('平台：Win only')
    L('')
    L('```csharp')
    L('void AddToRecentDocs(string filePath); void ClearRecentDocs();')
    L('```')
    L('')
    L('---')
    L('')
    L('## 15. WindowsAdmin 管理员检测')
    L('')
    L('平台：Win / Mac / Linux')
    L('')
    L('```csharp')
    L('bool IsRunningAsAdmin();')
    L('bool RestartAsAdmin(string args=null);  // Win: UAC; Linux: pkexec')
    L('```')
    L('')
    L('---')
    L('')
    L('## 16. WindowsTheme 主题DPI')
    L('')
    L('平台：Win / Mac / Linux')
    L('')
    L('```csharp')
    L('bool    IsDarkMode();')
    L('float   GetDpiScale();                      // 1.0=100%')
    L('float   GetDpiScaleForWindow(IntPtr hwnd);  // Win only')
    L('Color32 GetAccentColor();')
    L('```')
    L('')
    L('---')
    L('')
    L('## 17. ProcessHelper 进程工具')
    L('')
    L('平台：Win / Mac / Linux')
    L('v2：RunAndRead 改为 BeginOutputReadLine+BeginErrorReadLine 异步事件，消除管道死锁。')
    L('')
    L('```csharp')
    L('int     Run(string fileName, string arguments, int timeoutMs=5000);')
    L('string  RunAndRead(string fileName, string arguments, int timeoutMs=30000);')
    L('Process StartBackground(string fileName, string arguments);')
    L('string  Quote(string arg);')
    L('```')
    L('')
    L('---')
    L('')
    L('## 18. 接口层与平台实现')
    L('')
    L('### 接口层 (Assets/Plugins/Interfaces/)')
    L('')
    L('ITrayService / IFileDialog / IClipboard / IToastService / IMessageBox /')
    L('IShellService / IStartupService / IThemeService / ISingleInstance / ISystemInfo')
    L('')
    L('### 平台实现层 (Assets/Plugins/Platform/)')
    L('')
    L('| 类 | 说明 |')
    L('|----|------|')
    L('| NativeFileDialog / NullFileDialog | Win/Mac/Linux 委托 WindowsFileDialog |')
    L('| NativeClipboard / NullClipboard | Win=WindowsClipboard; 其他=GUIUtility |')
    L('| NativeToastService / NullToastService | 委托 WindowsToast |')
    L('| NativeMessageBox / NullMessageBox | 委托 WindowsMessageBox |')
    L('| NativeShellService / NullShellService | explorer / open / xdg-open |')
    L('| NativeSingleInstance / NullSingleInstance | 委托 WindowsSingleInstance |')
    L('')
    L('---')
    L('')
    L('## 平台支持矩阵')
    L('')
    L('| 模块 | Win | Mac | Linux |')
    L('|------|:---:|:---:|:-----:|')
    L('| NativePlatform | OK | OK | OK |')
    L('| TrayIconService | OK | OK | - |')
    L('| FileDialog | OK | OK | OK |')
    L('| MessageBox | OK | OK | OK |')
    L('| Clipboard | OK | OK | OK |')
    L('| Shell | OK | OK | OK |')
    L('| SingleInstance | OK | OK | OK |')
    L('| Hotkey | OK | - | - |')
    L('| Power | OK | OK | OK |')
    L('| RecycleBin | OK | OK | OK |')
    L('| Window 位置/置顶 | OK | OK | - |')
    L('| Window 最小化/最大化/透明度 | OK | OK | - |')
    L('| Startup | OK | OK | OK |')
    L('| SystemInfo | OK | OK | OK |')
    L('| Toast | OK | OK | OK |')
    L('| JumpList | OK | - | - |')
    L('| Admin | OK | OK | OK |')
    L('| Theme | OK | OK | OK |')
    L('| ProcessHelper | OK | OK | OK |')
    L('')
    L('---')
    L('')
    L('## 架构说明与优化日志')
    L('')
    L('### 目录结构')
    L('')
    L('```')
    L('Assets/Plugins/')
    L('├── NativePlatform.cs          <- 统一门面，推荐入口')
    L('├── Interfaces/                <- 10 个平台无关接口')
    L('├── Platform/                  <- Native*/Null* 实现对')
    L('├── ProcessHelper.cs           <- 异步读取，无死锁')
    L('├── TrayIconService.cs         <- Win/Mac #if 单文件')
    L('├── WindowsFileDialog.cs       <- Win/Mac osascript-stdin/Linux zenity')
    L('├── WindowsHotkey.cs           <- 完整 VK 常量表')
    L('├── WindowsSingleInstance.cs   <- Win Mutex / Mac-Linux 用户缓存锁文件')
    L('├── WindowsToast.cs            <- 内联命令，无临时文件')
    L('├── WindowsWindow.cs           <- Win/Mac 窗口控制')
    L('├── MacWindowPlugin.cs         <- Mac 插件封装')
    L('└── MacOS/MacTray/')
    L('    ├── MacTray.h              <- ObjC 头 (新增 Minimize/Maximize/SetAlpha)')
    L('    └── MacTray.m              <- ObjC 实现 (dispatch_sync 主线程安全)')
    L('```')
    L('')
    L('### v2 优化日志')
    L('')
    L('| 文件 | 问题 | 修复方案 |')
    L('|------|------|----------|')
    L('| ProcessHelper.cs | RunAndRead 管道缓冲满时死锁 | BeginOutputReadLine + BeginErrorReadLine 异步事件 |')
    L('| TrayIconService.cs | 三份重复代码 | 单文件 #if，公共 API 提顶层 |')
    L('| MacTray.h/m | 缺 Minimize/Maximize/SetAlpha | 新增 6 函数，dispatch_sync 安全 |')
    L('| MacWindowPlugin.cs | 缺对应绑定 | 新增 DllImport + 包装 |')
    L('| WindowsWindow.cs | Mac 缺窗口状态 API | 委托 MacWindowPlugin |')
    L('| WindowsToast.cs | Win 写临时 .ps1 | 改内联 -Command |')
    L('| WindowsFileDialog.cs | macOS 写临时 .scpt | 改 osascript stdin |')
    L('| WindowsSingleInstance.cs | 锁文件在 /tmp | Mac: ~/Library/Caches; Linux: ~/.cache |')
    L('| WindowsHotkey.cs | VK 常量不完整 | 补全 F1-F24/字母/数字/方向/媒体/浏览器/符号 |')
    L('')
    L('### 设计原则')
    L('')
    L('1. 接口驱动：业务代码依赖 I* 接口，便于测试和替换')
    L('2. 空对象模式：不支持平台返回 Null*，不抛异常')
    L('3. 门面模式：NativePlatform 统一入口，屏蔽平台差异')
    L('4. 零死锁：ProcessHelper.RunAndRead 异步事件消费 stdout/stderr')
    L('5. 无临时文件：Toast/FileDialog 均内联命令执行')
    L('')
    L('### 注意事项')
    L('')
    L('1. TrayIconService.Initialize() 必须在 Unity 主线程调用')
    L('2. Mac 托盘和窗口功能依赖编译好的 MacTray.bundle')
    L('3. Linux 依赖：zenity / notify-send / xdg-open / gio / systemd-inhibit')
    L('4. 文件对话框阻塞主线程直到用户操作完成')
    L('5. 不支持平台返回 false/null/0 并输出 LogWarning')
    return '\n'.join(lines) + '\n'

part_b = make_part_b()
with open(r'd:\UniToolGUI\Assets\Plugins\API.md', 'a', encoding='utf-8') as f:
    f.write(part_b)
print('part_b appended, lines:', part_b.count('\n'))
