# -*- coding: utf-8 -*-
import io
out = io.StringIO()
def w(s=''): out.write(s + '\n')

w('# UniToolGUI Plugins - 完整技术文档')
w()
w('> 跨平台系统集成 API，支持 Windows / macOS / Linux。')
w('> 推荐入口：NativePlatform 门面类；底层静态类仍可直接调用。')
w()
w('---')
w()
w('## 目录')
w()
for i,s in enumerate([
    '0. 统一入口 NativePlatform',
    '1. 系统托盘 TrayIconService',
    '2. 文件对话框 WindowsFileDialog',
    '3. 消息框 WindowsMessageBox',
    '4. 剪贴板 WindowsClipboard',
    '5. Shell 操作 WindowsShell',
    '6. 单实例 WindowsSingleInstance',
    '7. 全局热键 WindowsHotkey',
    '8. 电源控制 WindowsPower',
    '9. 回收站 WindowsRecycleBin',
    '10. 窗口控制 WindowsWindow',
    '11. 开机自启 WindowsStartup',
    '12. 系统信息 WindowsSystemInfo',
    '13. Toast 通知 WindowsToast',
    '14. Jump List WindowsJumpList',
    '15. 管理员检测 WindowsAdmin',
    '16. 主题与DPI WindowsTheme',
    '17. 进程工具 ProcessHelper',
    '18. 接口层与平台实现',
    '平台支持矩阵',
    '架构说明与优化日志',
]):
    anchor = s.split(' ')[0].lower().replace('.', '')
    w(f'- [{s}](#{anchor})')

w()
w('---')
w()
# Section 0
w('## 0. 统一入口 NativePlatform')
w()
w('平台：Win / Mac / Linux (不支持功能返回空实现，不抛异常)')
w()
w('```csharp')
w('bool NativePlatform.IsWindows / IsMacOS / IsLinux')
w()
w('// 服务访问器（懒加载）')
w('IFileDialog     NativePlatform.FileDialog')
w('IClipboard      NativePlatform.Clipboard')
w('IToastService   NativePlatform.Toast')
w('IMessageBox     NativePlatform.MessageBox')
w('IShellService   NativePlatform.Shell')
w('ISingleInstance NativePlatform.SingleInstance')
w('ITrayService    NativePlatform.Tray')
w()
w('// 便捷方法')
w('bool   NativePlatform.ShowToast(title, message, imagePath=null)')
w('string NativePlatform.OpenFile(title, filter, ext=null, dir=null)')
w('string NativePlatform.OpenFolder(title, dir=null)')
w('bool   NativePlatform.OpenUrl(url)')
w('string NativePlatform.GetClipboard()')
w('bool   NativePlatform.SetClipboard(text)')
w('```')
w()
w('```csharp')
w('// 典型启动流程')
w('if (!NativePlatform.SingleInstance.TryAcquire("MyApp")) { Application.Quit(); return; }')
w('NativePlatform.Tray.Initialize();')
w('NativePlatform.Tray.SetTooltip("我的应用");')
w('NativePlatform.ShowToast("启动", "应用已就绪");')
w('void OnApplicationQuit() {')
w('    NativePlatform.SingleInstance.Release();')
w('    NativePlatform.Tray.Shutdown();')
w('}')
w('```')
w()
w('---')
w()
# Section 1
w('## 1. 系统托盘 TrayIconService')
w()
w('平台：Win / Mac | 接口：ITrayService | 入口：NativePlatform.Tray')
w()
w('v2 变更：重构为单文件 #if 多平台，消除三份重复代码；Mac 委托 MacTrayPlugin。')
w()
w('```csharp')
w('void Initialize();   // 主线程调用')
w('void Shutdown();')
w('void SetTooltip(string tooltip);')
w('void RegisterMenuItems(IEnumerable<TrayMenuItem> items);')
w('void UnregisterMenuItems(IEnumerable<TrayMenuItem> items);')
w('void ClearMenuItems(); void RefreshMenu(); void ShowMainWindow();')
w('void ShowBalloonTip(string title, string message, uint iconType=1, uint timeoutMs=5000);')
w('event Action OnTrayIconCreated / OnTrayIconDestroyed;')
w('event Action<int> OnHotkeyPressed;  // Win only')
w('```')
w()
w('TrayMenuItem: Text, Callback, IsSeparator, IsToggle, Checked')
w()
w('```csharp')
w('var tray = NativePlatform.Tray;')
w('tray.Initialize();')
w('tray.RegisterMenuItems(new[]{')
w('    new TrayMenuItem { Text="显示", Callback=()=>tray.ShowMainWindow() },')
w('    new TrayMenuItem { IsSeparator=true },')
w('    new TrayMenuItem { Text="功能", IsToggle=true },')
w('    new TrayMenuItem { IsSeparator=true },')
w('    new TrayMenuItem { Text="退出", Callback=()=>Application.Quit() }')
w('});')
w('```')
w()
w('---')
w()
# Section 2
w('## 2. 文件对话框 WindowsFileDialog')
w()
w('平台：Win / Mac / Linux | 接口：IFileDialog | 入口：NativePlatform.FileDialog')
w()
w('v2 变更：macOS 改为 osascript stdin 内联执行，无临时文件；Linux 补全 SaveFilePanel/OpenFolderPanel。')
w()
w('```csharp')
w('string   CreateFilter(params string[] filterPairs);')
w('string   OpenFilePanel(string title, string filter, string ext=null, string dir=null);')
w('string[] OpenFilePanelMulti(string title, string filter, string ext=null, string dir=null);')
w('string   SaveFilePanel(string title, string filter, string ext=null, string dir=null, string name=null);')
w('string   OpenFolderPanel(string title, string dir=null);')
w('```')
w()
w('```csharp')
w('var dlg = NativePlatform.FileDialog;')
w('var f = dlg.CreateFilter("图片", "*.png;*.jpg", "所有文件", "*.*");')
w('string path = dlg.OpenFilePanel("选择", f, "png");')
w('string save = dlg.SaveFilePanel("保存", f, "png", null, "output");')
w('string folder = dlg.OpenFolderPanel("选择目录");')
w('```')
w()
w('---')
w()
# Section 3
w('## 3. 消息框 WindowsMessageBox')
w()
w('平台：Win / Mac / Linux | 接口：IMessageBox | 入口：NativePlatform.MessageBox')
w()
w('```csharp')
w('void Info(string text, string caption="信息");')
w('void Warning(string text, string caption="警告");')
w('void Error(string text, string caption="错误");')
w('bool Confirm(string text, string caption="确认");  // true=OK')
w('bool YesNo(string text, string caption="请选择");  // true=Yes')
w('int  Show(IntPtr hWnd, string text, string caption, int buttons=0, int icon=0);')
w('```')
w()
w('---')
w()
# Section 4
w('## 4. 剪贴板 WindowsClipboard')
w()
w('平台：Win / Mac / Linux | 接口：IClipboard | 入口：NativePlatform.Clipboard')
w()
w('```csharp')
w('string GetText();')
w('bool   SetText(string text);')
w('bool   HasText();')
w('```')
w()
w('---')
w()
# Section 5
w('## 5. Shell 操作 WindowsShell')
w()
w('平台：Win / Mac / Linux | 接口：IShellService | 入口：NativePlatform.Shell')
w()
w('```csharp')
w('bool OpenUrl(string url);')
w('bool OpenFile(string filePath);')
w('bool OpenFolder(string folderPath, string filePath=null);')
w('bool Execute(string operation, string filePath, string parameters=null, string workingDir=null);')
w('```')
w()
w('---')
w()
# Section 6
w('## 6. 单实例 WindowsSingleInstance')
w()
w('平台：Win (Global Mutex) / Mac (~/Library/Caches) / Linux (~/.cache)')
w('接口：ISingleInstance | 入口：NativePlatform.SingleInstance')
w()
w('v2 变更：Mac/Linux 锁文件路径从 /tmp 改为用户私有缓存目录，避免系统清理和跨用户污染。')
w()
w('```csharp')
w('bool TryAcquire(string mutexName=null);  // false=已有实例')
w('void Release();')
w('bool IsAnotherInstanceRunning(string mutexName=null);')
w('```')
w()
w('---')
w()
# Section 7
w('## 7. 全局热键 WindowsHotkey')
w()
w('平台：Win only')
w()
w('v2 变更：补全完整 VK 常量表（F1-F24, A-Z, D0-D9, Numpad0-9, 方向键, 导航键, 媒体键, 浏览器键, 符号键）；')
w('非 Windows 平台提供同签名空实现，编译不报错。')
w()
w('```csharp')
w('bool   Register(IntPtr hwnd, int id, ModifierKeys modifiers, uint virtualKey);')
w('bool   Unregister(IntPtr hwnd, int id);')
w('IntPtr GetUnityWindowHandle();')
w()
w('// ModifierKeys: None | Alt | Ctrl | Shift | Win | NoRepeat')
w('// VK.*: F1-F24 | A-Z | D0-D9 | Numpad0-9 | Multiply/Add/Subtract/Divide')
w('//       Left/Up/Right/Down | Home/End/PageUp/PageDown/Insert/Delete')
w('//       Space/Enter/Escape/Tab/BackSpace/CapsLock/NumLock/ScrollLock')
w('//       MediaNextTrack/MediaPrevTrack/MediaStop/MediaPlayPause')
w('//       VolumeUp/VolumeDown/VolumeMute')
w('//       BrowserBack/BrowserForward/BrowserRefresh/BrowserStop/BrowserSearch/BrowserHome')
w('//       OemSemicolon/OemPlus/OemComma/OemMinus/OemPeriod/OemQuestion/OemTilde')
w('//       OemOpenBracket/OemBackslash/OemCloseBracket/OemQuote')
w('```')
w()
w('```csharp')
w('var hwnd = WindowsHotkey.GetUnityWindowHandle();')
w('WindowsHotkey.Register(hwnd, 1,')
w('    WindowsHotkey.ModifierKeys.Ctrl | WindowsHotkey.ModifierKeys.Shift,')
w('    WindowsHotkey.VK.F1);')
w('NativePlatform.Tray.OnHotkeyPressed += id => { if (id==1) ShowWindow(); };')
w('void OnApplicationQuit() => WindowsHotkey.Unregister(hwnd, 1);')
w('```')
w()
w('---')
w()
w('## 8. 电源控制 WindowsPower')
w()
w('平台：Win / Mac / Linux')
w()
w('```csharp')
w('void PreventSleep();            // 防止休眠（显示器可关）')
w('void PreventSleepAndDisplay();  // 防止休眠 + 保持显示器')
w('void AllowSleep();              // 恢复默认')
w('void ResetIdleTimer();          // 临时重置空闲计时器')
w('```')
w()
w('---')
w()
w('## 9. 回收站 WindowsRecycleBin')
w()
w('平台：Win / Mac / Linux')
w()
w('```csharp')
w('int MoveToRecycleBin(string path, bool showConfirm=true);  // 0=成功')
w('int MoveToRecycleBinSilent(string path);  // 多文件：路径以 \\0 分隔')
w('```')
w()
return_val = out.getvalue()
with open(r'd:\UniToolGUI\api_part1.txt', 'w', encoding='utf-8') as f:
    f.write(return_val)
print('part1 done, chars:', len(return_val))
