# -*- coding: utf-8 -*-
import io
out = io.StringIO()
def w(s): out.write(s + '\n')

w('using System;')
w('using System.Collections.Generic;')
w('using System.Runtime.InteropServices;')
w('using System.Threading;')
w('using UnityEngine;')
w('')
w('public class TrayIconService')
w('{')
w('    private static readonly object _lock = new object();')
w('    private static TrayIconService _instance;')
w('    public static TrayIconService Instance')
w('    {')
w('        get { if (_instance==null) lock(_lock) if (_instance==null) _instance=new TrayIconService(); return _instance; }')
w('    }')
w('')
w('    public event Action OnTrayIconCreated;')
w('    public event Action OnTrayIconDestroyed;')
w('    public event Action<int> OnHotkeyPressed;')
w('')
w('    private readonly List<TrayMenuItem> _menuItems = new List<TrayMenuItem>();')
w('    private string _tooltip = "Unity App";')
w('    private bool   _initialized;')
w('    private TrayIconService() { }')
w('')
w('    public void Initialize()   { if (_initialized) return; PlatformInitialize(); }')
w('    public void Shutdown()     { if (!_initialized) return; PlatformShutdown(); }')
w('    public void SetTooltip(string t) { _tooltip = t ?? "Unity App"; if (_initialized) PlatformSetTooltip(_tooltip); }')
w('    public void RegisterMenuItems(IEnumerable<TrayMenuItem> items)   { foreach (var i in items) _menuItems.Add(i); if (_initialized) PlatformRebuildMenu(); }')
w('    public void UnregisterMenuItems(IEnumerable<TrayMenuItem> items) { foreach (var i in items) _menuItems.Remove(i); if (_initialized) PlatformRebuildMenu(); }')
w('    public void ClearMenuItems()  { _menuItems.Clear(); if (_initialized) PlatformRebuildMenu(); }')
w('    public void RefreshMenu()     { if (_initialized) PlatformRebuildMenu(); }')
w('    public void ShowMainWindow()  { if (_initialized) PlatformShowMainWindow(); }')
w('    public void ShowBalloonTip(string title, string message, uint iconType=1, uint timeoutMs=5000)')
w('        { if (_initialized) PlatformShowBalloon(title, message, iconType, timeoutMs); }')
w('')
w('    void FireCreated()      => OnTrayIconCreated?.Invoke();')
w('    void FireDestroyed()    => OnTrayIconDestroyed?.Invoke();')
w('    void FireHotkey(int id) => OnHotkeyPressed?.Invoke(id);')
w('')
w('#if UNITY_STANDALONE_WIN || UNITY_EDITOR_WIN')
w('    // ---- Win32 fields ----')
w('    private readonly Dictionary<uint,TrayMenuItem> _menuItemById = new Dictionary<uint,TrayMenuItem>();')
w('    private uint   _nextId = 1000;')
w('    private IntPtr _hwnd, _oldWndProc, _hMenu;')
w('    private WndProcDelegate _newWndProc;')
w('    private SynchronizationContext _mainCtx;')
w('    private bool _trayAdded;')
w('    const uint TRAY_ID = 100;')
w('')
w('    [DllImport("user32.dll",SetLastError=true)] static extern IntPtr FindWindow(string c,string t);')
w('    [DllImport("user32.dll")] static extern bool ShowWindow(IntPtr h,int n);')
w('    [DllImport("user32.dll")] static extern IntPtr SetWindowLongPtr(IntPtr h,int i,IntPtr v);')
w('    [DllImport("user32.dll")] static extern IntPtr CallWindowProc(IntPtr p,IntPtr h,uint m,IntPtr w,IntPtr l);')
w('    [DllImport("user32.dll")] static extern bool GetCursorPos(out POINT pt);')
w('    [DllImport("user32.dll")] static extern bool SetForegroundWindow(IntPtr h);')
w('    [DllImport("user32.dll")] static extern bool PostMessage(IntPtr h,uint m,IntPtr w,IntPtr l);')
w('    [DllImport("shell32.dll",CharSet=CharSet.Auto)] static extern bool Shell_NotifyIcon(uint d,ref NOTIFYICONDATA n);')
w('    [DllImport("user32.dll",CharSet=CharSet.Auto)] static extern IntPtr LoadIcon(IntPtr h,IntPtr n);')
w('    [DllImport("user32.dll")] static extern IntPtr CreatePopupMenu();')
w('    [DllImport("user32.dll",CharSet=CharSet.Auto)] static extern bool AppendMenu(IntPtr h,uint f,uint id,string s);')
w('    [DllImport("user32.dll")] static extern bool TrackPopupMenu(IntPtr h,uint f,int x,int y,int r,IntPtr w,IntPtr p);')
w('    [DllImport("user32.dll")] static extern bool DestroyMenu(IntPtr h);')
w('')
w('    const int  GWL_WNDPROC=-4;')
w('    const int  SW_HIDE=0,SW_SHOW=5,SW_RESTORE=9;')
w('    const uint WM_SIZE=5,WM_CLOSE=0x10,WM_COMMAND=0x111,WM_HOTKEY=0x312;')
w('    const uint WM_TRAYICON=0x500,WM_LBUTTONDBLCLK=0x203,WM_RBUTTONUP=0x205,WM_NULL=0;')
w('    const uint SIZE_MIN=1,NIM_ADD=0,NIM_DEL=2,NIM_MOD=1;')
w('    const uint NIF_MSG=1,NIF_ICO=2,NIF_TIP=4,NIF_INFO=0x10;')
w('    const uint MF_STR=0,MF_SEP=0x800,MF_CHK=8,TPM_RB=2;')
w('    static readonly IntPtr IDI_APP = new IntPtr(32512);')
w('')
w('    [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Auto)]')
w('    struct NOTIFYICONDATA {')
w('        public uint cbSize; public IntPtr hWnd; public uint uID;')
w('        public uint uFlags; public uint uCallbackMessage; public IntPtr hIcon;')
w('        [MarshalAs(UnmanagedType.ByValTStr,SizeConst=128)] public string szTip;')
w('        public uint dwState,dwStateMask;')
w('        [MarshalAs(UnmanagedType.ByValTStr,SizeConst=256)] public string szInfo;')
w('        public uint uTimeout;')
w('        [MarshalAs(UnmanagedType.ByValTStr,SizeConst=64)] public string szInfoTitle;')
w('        public uint dwInfoFlags; public Guid guidItem; public IntPtr hBalloonIcon;')
w('    }')
w('    [StructLayout(LayoutKind.Sequential)] struct POINT { public int x,y; }')
w('    delegate IntPtr WndProcDelegate(IntPtr h,uint m,IntPtr w,IntPtr l);')
w('')
w('    void PlatformInitialize() {')
w('        _mainCtx = SynchronizationContext.Current ?? new SynchronizationContext();')
w('        _hwnd = GetUnityHwnd();')
w('        if (_hwnd==IntPtr.Zero) { Debug.LogError("[Tray] no window"); return; }')
w('        _newWndProc = WndProc;')
w('        _oldWndProc = SetWindowLongPtr(_hwnd, GWL_WNDPROC, Marshal.GetFunctionPointerForDelegate(_newWndProc));')
w('        var n=MakeNid(); n.uFlags=NIF_MSG|NIF_ICO|NIF_TIP; n.uCallbackMessage=WM_TRAYICON;')
w('        n.hIcon=LoadIcon(IntPtr.Zero,IDI_APP); n.szTip=_tooltip;')
w('        if (Shell_NotifyIcon(NIM_ADD,ref n)) { _trayAdded=true; RebuildWin(); FireCreated(); }')
w('        else Debug.LogError("[Tray] Shell_NotifyIcon failed");')
w('        _initialized=true;')
w('    }')
w('    void PlatformShutdown() {')
w('        if (_trayAdded) { var n=MakeNid(); Shell_NotifyIcon(NIM_DEL,ref n); _trayAdded=false; }')
w('        if (_hMenu!=IntPtr.Zero) { DestroyMenu(_hMenu); _hMenu=IntPtr.Zero; }')
w('        if (_oldWndProc!=IntPtr.Zero) SetWindowLongPtr(_hwnd,GWL_WNDPROC,_oldWndProc);')
w('        _initialized=false; FireDestroyed();')
w('    }')
w('    void PlatformSetTooltip(string tip) { var n=MakeNid(); n.uFlags=NIF_TIP; n.szTip=tip; Shell_NotifyIcon(NIM_MOD,ref n); }')
w('    void PlatformRebuildMenu()    => RebuildWin();')
w('    void PlatformShowMainWindow() { ShowWindow(_hwnd,SW_SHOW); ShowWindow(_hwnd,SW_RESTORE); SetForegroundWindow(_hwnd); }')
w('    void PlatformShowBalloon(string title,string msg,uint iconType,uint ms) {')
w('        var n=MakeNid(); n.uFlags=NIF_INFO; n.szInfoTitle=title??""; n.szInfo=msg??""; n.dwInfoFlags=iconType; n.uTimeout=ms;')
w('        Shell_NotifyIcon(NIM_MOD,ref n);')
w('    }')
w('    static IntPtr GetUnityHwnd() {')
w('        try { var h=System.Diagnostics.Process.GetCurrentProcess().MainWindowHandle; if(h!=IntPtr.Zero) return h; } catch {}')
w('        var w=FindWindow("UnityWndClass",null); return w!=IntPtr.Zero?w:FindWindow("UnityContainerWndClass",null);')
w('    }')
w('    NOTIFYICONDATA MakeNid() { var n=new NOTIFYICONDATA(); n.cbSize=(uint)Marshal.SizeOf(n); n.hWnd=_hwnd; n.uID=TRAY_ID; return n; }')
w('    void RebuildWin() {')
w('        if (_hMenu!=IntPtr.Zero) DestroyMenu(_hMenu);')
w('        _hMenu=CreatePopupMenu(); _menuItemById.Clear();')
w('        foreach (var item in _menuItems) {')
w('            if (item.IsSeparator) { AppendMenu(_hMenu,MF_SEP,0,null); }')
w('            else { uint id=_nextId++; _menuItemById[id]=item;')
w('                   uint f=MF_STR; if(item.IsToggle&&item.Checked) f|=MF_CHK;')
w('                   AppendMenu(_hMenu,f,id,item.Text); }')
w('        }')
w('    }')
w('    IntPtr WndProc(IntPtr hWnd,uint msg,IntPtr wParam,IntPtr lParam) {')
w('        switch(msg) {')
w('            case WM_SIZE: if((uint)wParam==SIZE_MIN){ShowWindow(_hwnd,SW_HIDE);return IntPtr.Zero;} break;')
w('            case WM_CLOSE: ShowWindow(_hwnd,SW_HIDE); return IntPtr.Zero;')
w('            case WM_TRAYICON:')
w('                if((uint)lParam==WM_RBUTTONUP) { if(_hMenu!=IntPtr.Zero){GetCursorPos(out POINT pt);SetForegroundWindow(_hwnd);TrackPopupMenu(_hMenu,TPM_RB,pt.x,pt.y,0,_hwnd,IntPtr.Zero);PostMessage(_hwnd,WM_NULL,IntPtr.Zero,IntPtr.Zero);} }')
w('                else if((uint)lParam==WM_LBUTTONDBLCLK) PlatformShowMainWindow();')
w('                break;')
w('            case WM_HOTKEY: FireHotkey((int)wParam); return IntPtr.Zero;')
w('            case WM_COMMAND:')
w('                uint cmd=(uint)wParam&0xFFFF;')
w('                if (_menuItemById.TryGetValue(cmd,out var mi)) {')
w('                    if (mi.IsToggle) { mi.Checked=!mi.Checked; RebuildWin(); }')
w('                    _mainCtx.Post(_=>mi.Callback?.Invoke(),null);')
w('                } break;')
w('        }')
w('        return CallWindowProc(_oldWndProc,hWnd,msg,wParam,lParam);')
w('    }')
w('')
w('#elif UNITY_STANDALONE_OSX')
w('    void PlatformInitialize() {')
w('        if (!MacTrayPlugin.Init()) { Debug.LogError("[Tray] Mac init failed"); return; }')
w('        MacTrayPlugin.SetTooltip(_tooltip); MacTrayPlugin.SetMenu(_menuItems);')
w('        _initialized=true; FireCreated();')
w('        Debug.Log("[TrayIconService] macOS 初始化完成");')
w('    }')
w('    void PlatformShutdown()       { MacTrayPlugin.Shutdown(); _initialized=false; FireDestroyed(); }')
w('    void PlatformSetTooltip(string tip) => MacTrayPlugin.SetTooltip(tip);')
w('    void PlatformRebuildMenu()    => MacTrayPlugin.SetMenu(_menuItems);')
w('    void PlatformShowMainWindow() => MacTrayPlugin.ShowMainWindow();')
w('    void PlatformShowBalloon(string title,string msg,uint _1,uint _2) => MacTrayPlugin.ShowBalloon(title??"",msg??"");')
w('')
w('#else')
w('    void PlatformInitialize() { Debug.LogWarning("[TrayIconService] 托盘功能仅支持 Windows 和 macOS"); }')
w('    void PlatformShutdown() { }')
w('    void PlatformSetTooltip(string t) { }')
w('    void PlatformRebuildMenu() { }')
w('    void PlatformShowMainWindow() { }')
w('    void PlatformShowBalloon(string a,string b,uint c,uint d) { }')
w('#endif')
w('}')
w('')
w('/// <summary>托盘菜单项</summary>')
w('public class TrayMenuItem')
w('{')
w('    public string Text      { get; set; }')
w('    public Action Callback  { get; set; }')
w('    public bool IsSeparator { get; set; }')
w('    public bool IsToggle    { get; set; }')
w('    public bool Checked     { get; set; }')
w('}')

with open(r'd:\UniToolGUI\Assets\Plugins\TrayIconService.cs', 'w', encoding='utf-8') as f:
    f.write(out.getvalue())
print('done, chars:', len(out.getvalue()), 'lines:', out.getvalue().count('\n'))
