# -*- coding: utf-8 -*-
import io
out = io.StringIO()
def w(s): out.write(s + '\n')

w('using System;')
w('using System.Diagnostics;')
w('using System.Runtime.InteropServices;')
w('using System.Text;')
w('using UnityEngine;')
w('')
w('/// <summary>')
w('/// 文件/文件夹选择对话框（Win/Mac/Linux）。')
w('/// Windows : Win32 GetOpenFileName / GetSaveFileName / SHBrowseForFolder。')
w('/// macOS   : osascript via stdin（无临时文件，无磁盘IO竞态）。')
w('/// Linux   : zenity。')
w('/// </summary>')
w('public static class WindowsFileDialog')
w('{')
w('#if UNITY_STANDALONE_WIN || UNITY_EDITOR_WIN')
w('    #region Win32 常量与结构')
w('    private const int MAX_PATH        = 260;')
w('    private const int MAX_PATH_MULTI  = 65536;')
w('    private const int OFN_FILEMUSTEXIST    = 0x00001000;')
w('    private const int OFN_HIDEREADONLY     = 0x00000004;')
w('    private const int OFN_NOCHANGEDIR      = 0x00000008;')
w('    private const int OFN_OVERWRITEPROMPT  = 0x00000002;')
w('    private const int OFN_ALLOWMULTISELECT = 0x00000200;')
w('    private const int OFN_EXPLORER         = 0x00080000;')
w('    private const uint BIF_RETURNONLYFSDIRS = 0x0001;')
w('    private const uint BIF_NEWDIALOGSTYLE   = 0x0040;')
w('    private const uint BIF_EDITBOX          = 0x0010;')
w('    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]')
w('    private struct OPENFILENAME')
w('    {')
w('        public int    lStructSize;')
w('        public IntPtr hwndOwner;')
w('        public IntPtr hInstance;')
w('        public string lpstrFilter;')
w('        public string lpstrCustomFilter;')
w('        public int    nMaxCustFilter;')
w('        public int    nFilterIndex;')
w('        public string lpstrFile;')
w('        public int    nMaxFile;')
w('        public string lpstrFileTitle;')
w('        public int    nMaxFileTitle;')
w('        public string lpstrInitialDir;')
w('        public string lpstrTitle;')
w('        public int    Flags;')
w('        public short  nFileOffset;')
w('        public short  nFileExtension;')
w('        public string lpstrDefExt;')
w('        public IntPtr lCustData;')
w('        public IntPtr lpfnHook;')
w('        public string lpTemplateName;')
w('        public IntPtr pvReserved;')
w('        public int    dwReserved;')
w('        public int    flagsEx;')
w('    }')
w('    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Auto)]')
w('    private struct BROWSEINFOW')
w('    {')
w('        public IntPtr hwndOwner;')
w('        public IntPtr pidlRoot;')
w('        public string pszDisplayName;')
w('        public string lpszTitle;')
w('        public uint   ulFlags;')
w('        public IntPtr lpfn;')
w('        public IntPtr lParam;')
w('        public int    iImage;')
w('    }')
w('    #endregion')
w('    #region Win32 导入')
w('    [DllImport("comdlg32.dll", CharSet = CharSet.Auto, SetLastError = true)]')
w('    private static extern bool GetOpenFileName(ref OPENFILENAME ofn);')
w('    [DllImport("comdlg32.dll", CharSet = CharSet.Auto, SetLastError = true)]')
w('    private static extern bool GetSaveFileName(ref OPENFILENAME ofn);')
w('    [DllImport("shell32.dll", CharSet = CharSet.Auto)]')
w('    private static extern IntPtr SHBrowseForFolder(ref BROWSEINFOW lpbi);')
w('    [DllImport("shell32.dll", CharSet = CharSet.Auto)]')
w('    private static extern bool SHGetPathFromIDList(IntPtr pidl, IntPtr pszPath);')
w('    [DllImport("ole32.dll")]')
w('    private static extern void CoTaskMemFree(IntPtr hMem);')
w('    [DllImport("user32.dll")]')
w('    private static extern IntPtr GetActiveWindow();')
w('    #endregion')
w('')
w('    public static string OpenFilePanel(string title, string filter, string defaultExt = null, string initialDir = null)')
w('    {')
w('        var ofn = BuildOFN(filter, title, initialDir, defaultExt, MAX_PATH,')
w('            OFN_FILEMUSTEXIST | OFN_HIDEREADONLY | OFN_NOCHANGEDIR);')
w('        return GetOpenFileName(ref ofn) ? ofn.lpstrFile : null;')
w('    }')
w('')
w('    public static string[] OpenFilePanelMulti(string title, string filter, string defaultExt = null, string initialDir = null)')
w('    {')
w('        var ofn = BuildOFN(filter, title, initialDir, defaultExt, MAX_PATH_MULTI,')
w('            OFN_FILEMUSTEXIST | OFN_HIDEREADONLY | OFN_NOCHANGEDIR | OFN_ALLOWMULTISELECT | OFN_EXPLORER);')
w('        if (!GetOpenFileName(ref ofn)) return null;')
w(r"        var parts = ofn.lpstrFile.Split(new[] { '\0' }, StringSplitOptions.RemoveEmptyEntries);")
w('        if (parts.Length == 0) return null;')
w('        if (parts.Length == 1) return parts;')
w('        var dir = parts[0];')
w('        var files = new string[parts.Length - 1];')
w('        for (int i = 1; i < parts.Length; i++) files[i - 1] = System.IO.Path.Combine(dir, parts[i]);')
w('        return files;')
w('    }')
w('')
w('    public static string SaveFilePanel(string title, string filter, string defaultExt = null, string initialDir = null, string defaultFileName = null)')
w('    {')
w('        var ofn = BuildOFN(filter, title, initialDir, defaultExt, MAX_PATH, OFN_OVERWRITEPROMPT | OFN_NOCHANGEDIR);')
w('        if (!string.IsNullOrEmpty(defaultFileName))')
w('        {')
w('            var buf = new char[MAX_PATH];')
w('            for (int i = 0; i < defaultFileName.Length && i < MAX_PATH - 1; i++) buf[i] = defaultFileName[i];')
w('            ofn.lpstrFile = new string(buf);')
w('        }')
w('        return GetSaveFileName(ref ofn) ? ofn.lpstrFile : null;')
w('    }')
w('')
w('    public static string OpenFolderPanel(string title, string initialDir = null)')
w('    {')
w('        var bi = new BROWSEINFOW')
w('        {')
w('            hwndOwner = GetActiveWindow(), lpszTitle = title,')
w('            ulFlags = BIF_RETURNONLYFSDIRS | BIF_NEWDIALOGSTYLE | BIF_EDITBOX,')
w('            pszDisplayName = new string(new char[MAX_PATH])')
w('        };')
w('        IntPtr pidl = SHBrowseForFolder(ref bi);')
w('        if (pidl == IntPtr.Zero) return null;')
w('        IntPtr pPath = Marshal.AllocHGlobal(MAX_PATH * 2);')
w('        try { return SHGetPathFromIDList(pidl, pPath) ? Marshal.PtrToStringAuto(pPath) : null; }')
w('        finally { Marshal.FreeHGlobal(pPath); CoTaskMemFree(pidl); }')
w('    }')
w('')
w('    public static string CreateFilter(params string[] filterPairs)')
w('    {')
w('        if (filterPairs == null || filterPairs.Length % 2 != 0)')
w('            throw new ArgumentException("必须提供成对的描述和模式");')
w('        var sb = new StringBuilder();')
w(r"        for (int i = 0; i < filterPairs.Length; i += 2) { sb.Append(filterPairs[i]); sb.Append('\0'); sb.Append(filterPairs[i + 1]); sb.Append('\0'); }")
w(r"        sb.Append('\0');")
w('        return sb.ToString();')
w('    }')
w('')
w('    private static OPENFILENAME BuildOFN(string filter, string title, string initialDir,')
w('        string defaultExt, int maxFile, int flags)')
w('    {')
w('        var ofn = new OPENFILENAME();')
w('        ofn.lStructSize = Marshal.SizeOf(ofn); ofn.hwndOwner = GetActiveWindow();')
w('        ofn.lpstrFilter = filter; ofn.lpstrFile = new string(new char[maxFile]); ofn.nMaxFile = maxFile;')
w('        ofn.lpstrTitle = title; ofn.lpstrInitialDir = initialDir;')
w('        ofn.lpstrDefExt = defaultExt; ofn.Flags = flags;')
w('        return ofn;')
w('    }')
w('')
w('#elif UNITY_STANDALONE_OSX')
w('    // ======================================================')
w('    // macOS: osascript via stdin - 无临时文件')
w('    // ======================================================')
w('')
w('    public static string OpenFilePanel(string title, string filter, string defaultExt = null, string initialDir = null)')
w('    {')
w('        var sb = new StringBuilder();')
w('        sb.Append("set theFile to (choose file");')
w('        AppendPrompt(sb, title); AppendExtensions(sb, filter); AppendDefaultLocation(sb, initialDir);')
w('        sb.Append(")\nreturn POSIX path of theFile");')
w('        return RunOsascriptInline(sb.ToString());')
w('    }')
w('')
w('    public static string[] OpenFilePanelMulti(string title, string filter, string defaultExt = null, string initialDir = null)')
w('    {')
w('        var sb = new StringBuilder();')
w('        sb.Append("set theFiles to (choose file with multiple selections allowed");')
w('        AppendPrompt(sb, title); AppendExtensions(sb, filter); AppendDefaultLocation(sb, initialDir);')
w('        sb.Append(")\nset out to \"\"\nrepeat with f in theFiles\n  set out to out & (POSIX path of f) & \"\n\"\nend repeat\nreturn out");')
w('        var result = RunOsascriptInline(sb.ToString());')
w('        if (string.IsNullOrEmpty(result)) return null;')
w(r"        return result.Split(new[] { '\n' }, StringSplitOptions.RemoveEmptyEntries);")
w('    }')
w('')
w('    public static string SaveFilePanel(string title, string filter, string defaultExt = null, string initialDir = null, string defaultFileName = null)')
w('    {')
w('        var sb = new StringBuilder();')
w('        sb.Append("set theFile to (choose file name");')
w('        AppendPrompt(sb, title);')
w('        if (!string.IsNullOrEmpty(defaultFileName))')
w('            sb.Append(" default name \"" + EscAS(defaultFileName) + "\"" );')
w('        AppendDefaultLocation(sb, initialDir);')
w('        sb.Append(")\nreturn POSIX path of theFile");')
w('        var result = RunOsascriptInline(sb.ToString());')
w('        if (result != null && !string.IsNullOrEmpty(defaultExt) && !result.Contains("."))')
w('            result += "." + defaultExt;')
w('        return result;')
w('    }')
w('')
w('    public static string OpenFolderPanel(string title, string initialDir = null)')
w('    {')
w('        var sb = new StringBuilder();')
w('        sb.Append("set theFolder to (choose folder");')
w('        AppendPrompt(sb, title); AppendDefaultLocation(sb, initialDir);')
w('        sb.Append(")\nreturn POSIX path of theFolder");')
w('        return RunOsascriptInline(sb.ToString());')
w('    }')
w('')
w('    public static string CreateFilter(params string[] filterPairs)')
w('    {')
w('        if (filterPairs == null || filterPairs.Length % 2 != 0)')
w('            throw new ArgumentException("必须提供成对的描述和模式");')
w('        var sb = new StringBuilder();')
w(r"        for (int i = 0; i < filterPairs.Length; i += 2) { sb.Append(filterPairs[i]); sb.Append('\0'); sb.Append(filterPairs[i + 1]); sb.Append('\0'); }")
w(r"        sb.Append('\0');")
w('        return sb.ToString();')
w('    }')
w('')
w('    private static void AppendPrompt(StringBuilder sb, string title)')
w('    {')
w('        if (!string.IsNullOrEmpty(title))')
w('            sb.Append(" with prompt \"" + EscAS(title) + "\"" );')
w('    }')
w('')
w('    private static void AppendDefaultLocation(StringBuilder sb, string dir)')
w('    {')
w('        if (!string.IsNullOrEmpty(dir))')
w(r'            sb.Append(" default location (POSIX file \"" + EscAS(dir.Replace("\\\\", "/")) + "\")");')
w('    }')
w('')
w('    private static void AppendExtensions(StringBuilder sb, string filter)')
w('    {')
w('        var exts = ParseExtensionsFromFilter(filter);')
w('        if (exts == null || exts.Length == 0) return;')
w('        sb.Append(" of type {");')
w('        for (int i = 0; i < exts.Length; i++)')
w('        {')
w('            if (i > 0) sb.Append(", ");')
w('            sb.Append("\"" + EscAS(exts[i]) + "\"" );')
w('        }')
w('        sb.Append("}");')
w('    }')
w('')
w('    /// <summary>')
w('    /// 通过 stdin 将 AppleScript 传给 osascript（osascript -）。')
w('    /// 无需写临时 .scpt 文件，无磁盘IO也无竞态风险。')
w('    /// </summary>')
w('    private static string RunOsascriptInline(string script)')
w('    {')
w('        try')
w('        {')
w('            var psi = new ProcessStartInfo')
w('            {')
w('                FileName = "osascript",')
w('                Arguments = "-",')
w('                UseShellExecute = false,')
w('                CreateNoWindow = true,')
w('                RedirectStandardInput  = true,')
w('                RedirectStandardOutput = true,')
w('                RedirectStandardError  = true,')
w('                StandardInputEncoding  = System.Text.Encoding.UTF8,')
w('                StandardOutputEncoding = System.Text.Encoding.UTF8,')
w('            };')
w('            using (var p = new Process { StartInfo = psi })')
w('            {')
w('                p.Start();')
w('                p.StandardInput.Write(script);')
w('                p.StandardInput.Close();')
w('                var output = p.StandardOutput.ReadToEnd();')
w('                p.WaitForExit(60000);')
w('                return string.IsNullOrWhiteSpace(output) ? null : output.Trim();')
w('            }')
w('        }')
w('        catch (Exception ex)')
w('        {')
w('            Debug.LogWarning("[WindowsFileDialog] osascript failed: " + ex.Message);')
w('            return null;')
w('        }')
w('    }')
w('')
w('    private static string EscAS(string s) =>')
w('        (s ?? "").Replace("\\\\", "\\\\\\\\").Replace("\"", "\\\"");')
w('')
w('    private static string[] ParseExtensionsFromFilter(string filter)')
w('    {')
w('        if (string.IsNullOrEmpty(filter)) return null;')
w("        var parts = filter.Split(new[] { '\\0' }, StringSplitOptions.RemoveEmptyEntries);")
w('        var exts = new System.Collections.Generic.List<string>();')
w('        for (int i = 1; i < parts.Length; i += 2)')
w("            foreach (var p2 in parts[i].Split(';'))")
w('            {')
w("                var ext = p2.Trim().TrimStart('*').TrimStart('.');")
w('                if (!string.IsNullOrEmpty(ext) && ext != "*") exts.Add(ext);')
w('            }')
w('        return exts.Count > 0 ? exts.ToArray() : null;')
w('    }')
w('')
w('#elif UNITY_STANDALONE_LINUX')
w('    public static string OpenFilePanel(string title, string filter, string defaultExt = null, string initialDir = null)')
w('    {')
w('        return ProcessHelper.RunAndRead("zenity",')
w('            BuildZenityArgs("--file-selection", title, initialDir, filter), 60000)?.TrimEnd(\'\\n\');')
w('    }')
w('')
w('    public static string[] OpenFilePanelMulti(string title, string filter, string defaultExt = null, string initialDir = null)')
w('    {')
w('        var result = ProcessHelper.RunAndRead("zenity",')
w('            BuildZenityArgs("--file-selection --multiple --separator=|", title, initialDir, filter), 60000);')
w("        return string.IsNullOrEmpty(result) ? null : result.Split(new[] { '|' }, StringSplitOptions.RemoveEmptyEntries);")
w('    }')
w('')
w('    public static string SaveFilePanel(string title, string filter, string defaultExt = null, string initialDir = null, string defaultFileName = null)')
w('    {')
w('        var args = new StringBuilder("--file-selection --save --confirm-overwrite");')
w('        if (!string.IsNullOrEmpty(title)) args.Append(" --title=" + ProcessHelper.Quote(title));')
w('        var path = initialDir ?? "";')
w('        if (!string.IsNullOrEmpty(defaultFileName))')
w('            path = string.IsNullOrEmpty(path) ? defaultFileName : System.IO.Path.Combine(path, defaultFileName);')
w('        if (!string.IsNullOrEmpty(path)) args.Append(" --filename=" + ProcessHelper.Quote(path));')
w('        AppendZenityFilters(args, filter);')
w('        var result = ProcessHelper.RunAndRead("zenity", args.ToString(), 60000)?.TrimEnd(\'\\n\');')
w('        if (result != null && !string.IsNullOrEmpty(defaultExt) && !result.Contains(".")) result += "." + defaultExt;')
w('        return result;')
w('    }')
w('')
w('    public static string OpenFolderPanel(string title, string initialDir = null)')
w('    {')
w('        return ProcessHelper.RunAndRead("zenity",')
w('            BuildZenityArgs("--file-selection --directory", title, initialDir, null), 60000)?.TrimEnd(\'\\n\');')
w('    }')
w('')
w('    public static string CreateFilter(params string[] filterPairs)')
w('    {')
w('        if (filterPairs == null || filterPairs.Length % 2 != 0)')
w('            throw new ArgumentException("必须提供成对的描述和模式");')
w('        var sb = new StringBuilder();')
w("        for (int i = 0; i < filterPairs.Length; i += 2) { sb.Append(filterPairs[i]); sb.Append('\\0'); sb.Append(filterPairs[i+1]); sb.Append('\\0'); }")
w("        sb.Append('\\0');")
w('        return sb.ToString();')
w('    }')
w('')
w('    private static string BuildZenityArgs(string mode, string title, string initialDir, string filter)')
w('    {')
w('        var sb = new StringBuilder(mode);')
w('        if (!string.IsNullOrEmpty(title)) sb.Append(" --title=" + ProcessHelper.Quote(title));')
w("        if (!string.IsNullOrEmpty(initialDir)) sb.Append(\" --filename=\" + ProcessHelper.Quote(initialDir.TrimEnd('/', '\\\\') + \"/\"));")
w('        AppendZenityFilters(sb, filter);')
w('        return sb.ToString();')
w('    }')
w('')
w('    private static void AppendZenityFilters(StringBuilder sb, string filter)')
w('    {')
w('        var exts = ParseExtensionsFromFilter(filter);')
w('        if (exts == null) return;')
w('        foreach (var ext in exts) sb.Append(" --file-filter=\\\"*." + ext + "\\\"");')
w('    }')
w('')
w('    private static string[] ParseExtensionsFromFilter(string filter)')
w('    {')
w('        if (string.IsNullOrEmpty(filter)) return null;')
w("        var parts = filter.Split(new[] { '\\0' }, StringSplitOptions.RemoveEmptyEntries);")
w('        var exts = new System.Collections.Generic.List<string>();')
w('        for (int i = 1; i < parts.Length; i += 2)')
w("            foreach (var p2 in parts[i].Split(';'))")
w('            {')
w("                var ext = p2.Trim().TrimStart('*').TrimStart('.');")
w('                if (!string.IsNullOrEmpty(ext) && ext != "*") exts.Add(ext);')
w('            }')
w('        return exts.Count > 0 ? exts.ToArray() : null;')
w('    }')
w('')
w('#else')
w('    public static string OpenFilePanel(string title, string filter, string defaultExt = null, string initialDir = null) => null;')
w('    public static string[] OpenFilePanelMulti(string title, string filter, string defaultExt = null, string initialDir = null) => null;')
w('    public static string SaveFilePanel(string title, string filter, string defaultExt = null, string initialDir = null, string defaultFileName = null) => null;')
w('    public static string OpenFolderPanel(string title, string initialDir = null) => null;')
w('    public static string CreateFilter(params string[] filterPairs)')
w('    {')
w('        if (filterPairs == null || filterPairs.Length % 2 != 0)')
w('            throw new ArgumentException("必须提供成对的描述和模式");')
w('        var sb = new StringBuilder();')
w("        for (int i = 0; i < filterPairs.Length; i += 2) { sb.Append(filterPairs[i]); sb.Append('\\0'); sb.Append(filterPairs[i+1]); sb.Append('\\0'); }")
w("        sb.Append('\\0');")
w('        return sb.ToString();')
w('    }')
w('#endif')
w('}')

with open(r'd:\UniToolGUI\Assets\Plugins\WindowsFileDialog.cs', 'w', encoding='utf-8') as f:
    f.write(out.getvalue())
print('done, chars:', len(out.getvalue()))