# -*- coding: utf-8 -*-
import io
out = io.StringIO()
def w(s): out.write(s + '\n')

w('using System;')
w('using System.Runtime.InteropServices;')
w('using UnityEngine;')
w('')
w('/// <summary>')
w('/// 窗口控制：置顶、位置/大小、最小化/最大化/还原、透明度（Win/Mac）。')
w('/// </summary>')
w('public static class WindowsWindow')
w('{')
w('#if UNITY_STANDALONE_WIN || UNITY_EDITOR_WIN')
w('    [DllImport("user32.dll",SetLastError=true)] static extern bool GetWindowRect(IntPtr h, out RECT r);')
w('    [DllImport("user32.dll",SetLastError=true)] static extern bool SetWindowPos(IntPtr h, IntPtr i, int x, int y, int cx, int cy, uint f);')
w('    [DllImport("user32.dll",SetLastError=true)] static extern IntPtr FindWindow(string c, string t);')
w('    [DllImport("user32.dll")] static extern bool ShowWindow(IntPtr h, int n);')
w('    [DllImport("user32.dll")] static extern bool IsIconic(IntPtr h);')
w('    [DllImport("user32.dll")] static extern bool IsZoomed(IntPtr h);')
w('    [DllImport("user32.dll",SetLastError=true)] static extern int  GetWindowLong(IntPtr h, int i);')
w('    [DllImport("user32.dll",SetLastError=true)] static extern int  SetWindowLong(IntPtr h, int i, int v);')
w('    [DllImport("user32.dll")] static extern bool SetLayeredWindowAttributes(IntPtr h, uint c, byte b, uint f);')
w('')
w('    [StructLayout(LayoutKind.Sequential)]')
w('    struct RECT { public int Left, Top, Right, Bottom; }')
w('')
w('    static readonly IntPtr HWND_TOPMOST   = new IntPtr(-1);')
w('    static readonly IntPtr HWND_NOTOPMOST = new IntPtr(-2);')
w('    const uint SWP_NOMOVE    = 0x0002;')
w('    const uint SWP_NOSIZE    = 0x0001;')
w('    const uint SWP_NOACTIVATE= 0x0010;')
w('    const int  SW_MINIMIZE   = 6;')
w('    const int  SW_MAXIMIZE   = 3;')
w('    const int  SW_RESTORE    = 9;')
w('    const int  GWL_EXSTYLE   = -20;')
w('    const int  WS_EX_LAYERED = 0x00080000;')
w('    const uint LWA_ALPHA     = 0x2;')
w('')
w('    public static IntPtr GetUnityWindowHandle()')
w('    {')
w('        try { var h = System.Diagnostics.Process.GetCurrentProcess().MainWindowHandle; if (h != IntPtr.Zero) return h; } catch { }')
w('        var wnd = FindWindow("UnityWndClass", null);')
w('        return wnd != IntPtr.Zero ? wnd : FindWindow("UnityContainerWndClass", null);')
w('    }')
w('')
w('    public static bool SetTopMost(IntPtr hwnd, bool topMost)')
w('        => SetWindowPos(hwnd, topMost ? HWND_TOPMOST : HWND_NOTOPMOST, 0,0,0,0, SWP_NOMOVE|SWP_NOSIZE|SWP_NOACTIVATE);')
w('')
w('    public static bool SetPositionAndSize(IntPtr hwnd, int x, int y, int width, int height)')
w('        => SetWindowPos(hwnd, IntPtr.Zero, x, y, width, height, SWP_NOACTIVATE);')
w('')
w('    public static bool GetPositionAndSize(IntPtr hwnd, out int x, out int y, out int width, out int height)')
w('    {')
w('        x = y = width = height = 0;')
w('        if (!GetWindowRect(hwnd, out RECT r)) return false;')
w('        x = r.Left; y = r.Top; width = r.Right - r.Left; height = r.Bottom - r.Top; return true;')
w('    }')
w('')
w('    public static bool Minimize(IntPtr hwnd)    => ShowWindow(hwnd, SW_MINIMIZE);')
w('    public static bool Maximize(IntPtr hwnd)    => ShowWindow(hwnd, SW_MAXIMIZE);')
w('    public static bool Restore(IntPtr hwnd)     => ShowWindow(hwnd, SW_RESTORE);')
w('    public static bool IsMinimized(IntPtr hwnd) => IsIconic(hwnd);')
w('    public static bool IsMaximized(IntPtr hwnd) => IsZoomed(hwnd);')
w('')
w('    public static bool SetOpacity(IntPtr hwnd, float opacity)')
w('    {')
w('        opacity = Mathf.Clamp01(opacity);')
w('        int ex = GetWindowLong(hwnd, GWL_EXSTYLE);')
w('        SetWindowLong(hwnd, GWL_EXSTYLE, ex | WS_EX_LAYERED);')
w('        return SetLayeredWindowAttributes(hwnd, 0, (byte)(opacity * 255), LWA_ALPHA);')
w('    }')
w('')
w('    // Unity 主窗口便捷方法')
w('    public static bool SetUnityWindowTopMost(bool t)                              => SetTopMost(GetUnityWindowHandle(), t);')
w('    public static bool GetUnityWindowRect(out int x,out int y,out int w,out int h) => GetPositionAndSize(GetUnityWindowHandle(),out x,out y,out w,out h);')
w('    public static bool SetUnityWindowRect(int x,int y,int w,int h)               => SetPositionAndSize(GetUnityWindowHandle(),x,y,w,h);')
w('    public static bool MinimizeUnityWindow()   => Minimize(GetUnityWindowHandle());')
w('    public static bool MaximizeUnityWindow()   => Maximize(GetUnityWindowHandle());')
w('    public static bool RestoreUnityWindow()    => Restore(GetUnityWindowHandle());')
w('    public static bool IsUnityWindowMinimized()=> IsMinimized(GetUnityWindowHandle());')
w('    public static bool IsUnityWindowMaximized()=> IsMaximized(GetUnityWindowHandle());')
w('    public static bool SetUnityWindowOpacity(float o) => SetOpacity(GetUnityWindowHandle(), o);')
w('')
w('#elif UNITY_STANDALONE_OSX')
w('    public static IntPtr GetUnityWindowHandle() => IntPtr.Zero;')
w('    public static bool SetTopMost(IntPtr h, bool t)                              => MacWindowPlugin.SetTopMost(t);')
w('    public static bool SetPositionAndSize(IntPtr h, int x, int y, int w, int ht) => MacWindowPlugin.SetFrame(x,y,w,ht);')
w('    public static bool GetPositionAndSize(IntPtr h, out int x, out int y, out int w, out int ht) => MacWindowPlugin.GetFrame(out x,out y,out w,out ht);')
w('    public static bool Minimize(IntPtr h)    => MacWindowPlugin.Minimize();')
w('    public static bool Maximize(IntPtr h)    => MacWindowPlugin.Maximize();')
w('    public static bool Restore(IntPtr h)     => MacWindowPlugin.Restore();')
w('    public static bool IsMinimized(IntPtr h) => MacWindowPlugin.IsMinimized();')
w('    public static bool IsMaximized(IntPtr h) => MacWindowPlugin.IsMaximized();')
w('    public static bool SetOpacity(IntPtr h, float o) => MacWindowPlugin.SetOpacity(o);')
w('    public static bool SetUnityWindowTopMost(bool t)                              => MacWindowPlugin.SetTopMost(t);')
w('    public static bool GetUnityWindowRect(out int x,out int y,out int w,out int h) => MacWindowPlugin.GetFrame(out x,out y,out w,out h);')
w('    public static bool SetUnityWindowRect(int x,int y,int w,int h)               => MacWindowPlugin.SetFrame(x,y,w,h);')
w('    public static bool MinimizeUnityWindow()   => MacWindowPlugin.Minimize();')
w('    public static bool MaximizeUnityWindow()   => MacWindowPlugin.Maximize();')
w('    public static bool RestoreUnityWindow()    => MacWindowPlugin.Restore();')
w('    public static bool IsUnityWindowMinimized()=> MacWindowPlugin.IsMinimized();')
w('    public static bool IsUnityWindowMaximized()=> MacWindowPlugin.IsMaximized();')
w('    public static bool SetUnityWindowOpacity(float o) => MacWindowPlugin.SetOpacity(o);')
w('')
w('#else')
w('    public static IntPtr GetUnityWindowHandle() => IntPtr.Zero;')
w('    public static bool SetTopMost(IntPtr h, bool t) => false;')
w('    public static bool SetPositionAndSize(IntPtr h,int x,int y,int w,int ht) => false;')
w('    public static bool GetPositionAndSize(IntPtr h,out int x,out int y,out int w,out int ht) { x=y=w=ht=0; return false; }')
w('    public static bool Minimize(IntPtr h) => false;')
w('    public static bool Maximize(IntPtr h) => false;')
w('    public static bool Restore(IntPtr h)  => false;')
w('    public static bool IsMinimized(IntPtr h) => false;')
w('    public static bool IsMaximized(IntPtr h) => false;')
w('    public static bool SetOpacity(IntPtr h, float o) => false;')
w('    public static bool SetUnityWindowTopMost(bool t) => false;')
w('    public static bool GetUnityWindowRect(out int x,out int y,out int w,out int h) { x=y=w=h=0; return false; }')
w('    public static bool SetUnityWindowRect(int x,int y,int w,int h) => false;')
w('    public static bool MinimizeUnityWindow()    => false;')
w('    public static bool MaximizeUnityWindow()    => false;')
w('    public static bool RestoreUnityWindow()     => false;')
w('    public static bool IsUnityWindowMinimized() => false;')
w('    public static bool IsUnityWindowMaximized() => false;')
w('    public static bool SetUnityWindowOpacity(float o) => false;')
w('#endif')
w('}')

with open(r'd:\UniToolGUI\Assets\Plugins\WindowsWindow.cs','w',encoding='utf-8') as f:
    f.write(out.getvalue())
print('done, chars:', len(out.getvalue()), 'lines:', out.getvalue().count('\n'))
